// Package admin serves the web interface that edits the configuration file.
//
// It writes the file and stops there. Applying the change is the job of the
// watcher in internal/supervisor, which notices the new file within
// general.reloadInterval seconds and hands it to the servers that are running,
// so the interface needs no hold over them at all.
//
// The form is not written by hand: it is generated by reflecting over
// config.Config, so a key added to the configuration appears in the browser
// with nothing else to do. See schema.go.
package admin

import (
	"context"
	"crypto/tls"
	"embed"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"log/slog"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"sync"
	"sync/atomic"

	"go-fs/internal/config"
	"go-fs/internal/service"
	"go-fs/internal/tlsconf"
)

//go:embed assets
var assets embed.FS

// maxPost caps the posted configuration, which is a few kilobytes of JSON.
const maxPost = 1 << 20

// Server serves the interface over TLS.
type Server struct {
	// snapshot holds what a reload may swap, which is the credentials. Every
	// request takes one at the top of ServeHTTP.
	snapshot atomic.Pointer[settings]

	// path is the file the interface reads and writes.
	path   string
	schema Schema
	log    *slog.Logger

	listener net.Listener
	server   *http.Server

	wg sync.WaitGroup

	mu       sync.Mutex
	shutdown bool
}

// settings is the part of the server a reload can replace.
type settings struct {
	cfg config.General
}

func (s *Server) settings() *settings {
	return s.snapshot.Load()
}

// Reload swaps the credentials. The address, the port, the scheme and the
// certificate cannot change under a bound listener, so those report
// ErrNeedsRestart.
func (s *Server) Reload(cfg config.General) error {
	current := s.settings()
	if cfg.AdminInterfaceEnabled != current.cfg.AdminInterfaceEnabled ||
		cfg.AdminInterfaceAddress != current.cfg.AdminInterfaceAddress ||
		cfg.AdminInterfacePort != current.cfg.AdminInterfacePort ||
		cfg.AdminInterfaceUseHTTPS != current.cfg.AdminInterfaceUseHTTPS ||
		cfg.AdminCert != current.cfg.AdminCert || cfg.AdminKey != current.cfg.AdminKey {
		return service.ErrNeedsRestart
	}
	s.snapshot.Store(&settings{cfg: cfg})
	return nil
}

// New prepares the interface. path is the configuration file it edits.
func New(cfg config.General, path string, logger *slog.Logger) (*Server, error) {
	if path == "" {
		return nil, errors.New("the admin interface needs the path of the configuration file")
	}
	schema, skipped := build()
	for _, name := range skipped {
		// a shape the generated form does not handle is said out loud rather
		// than quietly left out of the page
		logger.Warn("the admin interface cannot edit this setting", "field", name)
	}

	server := &Server{path: path, schema: schema, log: logger}
	server.snapshot.Store(&settings{cfg: cfg})
	server.server = &http.Server{
		Handler:  server,
		ErrorLog: slog.NewLogLogger(logger.Handler(), slog.LevelDebug),
	}
	return server, nil
}

// Start binds the listener and serves until ctx is cancelled.
//
// The interface is served over TLS unless general.adminInterfaceUseHttps was
// turned off, which is for putting a proxy that terminates TLS in front of it.
// The page carries every password in the file, so plain HTTP without such a
// proxy is warned about rather than left to be noticed.
func (s *Server) Start(ctx context.Context) error {
	set := s.settings()
	s.warnAboutTheTransport(set.cfg)

	address := net.JoinHostPort(set.cfg.AdminInterfaceAddress,
		strconv.Itoa(set.cfg.AdminInterfacePort))
	raw, err := net.Listen("tcp", address)
	if err != nil {
		return err
	}

	scheme := "http"
	s.listener = raw
	if set.cfg.AdminInterfaceUseHTTPS {
		// built only when it is going to be used, so that a plain HTTP setup
		// with no certificate on purpose is not warned about missing one
		tlsConfig, err := tlsconf.Build(set.cfg.AdminCert, set.cfg.AdminKey,
			"general.adminCert", "general.adminKey", s.log)
		if err != nil {
			_ = raw.Close()
			return err
		}
		scheme = "https"
		s.listener = tls.NewListener(raw, tlsConfig)
	}
	s.log.Info("admin interface listening", "scheme", scheme,
		"address", listenAddress(raw), "port", listenPort(raw))

	go func() {
		<-ctx.Done()
		_ = s.Shutdown(context.Background())
	}()

	s.wg.Add(1)
	go func() {
		defer s.wg.Done()
		if err := s.server.Serve(s.listener); err != nil &&
			!errors.Is(err, http.ErrServerClosed) && !errors.Is(err, net.ErrClosed) {
			s.log.Error("the admin interface stopped serving", "error", err)
		}
	}()
	return nil
}

// warnAboutTheTransport says what turning TLS off costs, at the moment the
// listener is bound.
//
// Plain HTTP is not refused: a proxy that terminates TLS is the reason the
// setting exists, and it may well be on another host. What is worth saying is
// that without such a proxy the admin account and every password on the page
// cross the network in the clear.
func (s *Server) warnAboutTheTransport(cfg config.General) {
	if cfg.AdminInterfaceUseHTTPS {
		return
	}
	if !isLoopback(cfg.AdminInterfaceAddress) {
		s.log.Warn("the admin interface is served over plain HTTP on an address that is "+
			"not the loopback one, so the admin account and every password on the page "+
			"cross the network in the clear unless a proxy terminates TLS in front of it",
			"address", cfg.AdminInterfaceAddress)
	}
	if cfg.AdminCert != "" || cfg.AdminKey != "" {
		s.log.Warn("general.adminCert and general.adminKey are set but not used, " +
			"because general.adminInterfaceUseHttps is off")
	}
}

// isLoopback reports an address that only the host itself can reach. An empty
// address binds every interface, so it is not one.
func isLoopback(address string) bool {
	if address == "" {
		return false
	}
	parsed := net.ParseIP(address)
	return parsed != nil && parsed.IsLoopback()
}

// Addr reports the bound address, which is useful when port 0 was asked for.
func (s *Server) Addr() net.Addr {
	if s.listener == nil {
		return nil
	}
	return s.listener.Addr()
}

// Shutdown closes the listener and drops every open connection.
func (s *Server) Shutdown(context.Context) error {
	s.mu.Lock()
	if s.shutdown {
		s.mu.Unlock()
		return nil
	}
	s.shutdown = true
	s.mu.Unlock()

	_ = s.server.Close()
	if s.listener != nil {
		_ = s.listener.Close()
	}
	s.wg.Wait()
	return nil
}

// state is what the page needs to render itself.
type state struct {
	Schema Schema         `json:"schema"`
	Values map[string]any `json:"values"`
	Path   string         `json:"path"`
	// Writable and WriteError report whether Apply can succeed at all, so that
	// a file that cannot be written says so before anything is edited.
	Writable   bool   `json:"writable"`
	WriteError string `json:"writeError,omitempty"`
	// Reload reports whether the file is watched. When it is not, a change is
	// written but only applies at the next restart, and the page says so.
	Reload bool `json:"reload"`
	// Summaries describes the values that hold key material, keyed
	// "ftps.cert", so the page shows what a base64 blob actually is.
	Summaries map[string]string `json:"summaries,omitempty"`
}

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	set := s.settings()
	if !s.authenticate(set, w, r) {
		return
	}

	switch {
	case r.URL.Path == "/api/config" && r.Method == http.MethodGet:
		s.handleState(w)
	case r.URL.Path == "/api/config" && r.Method == http.MethodPost:
		s.handleApply(w, r)
	case r.URL.Path == "/api/upload" && r.Method == http.MethodPost:
		s.handleUpload(w, r)
	case r.URL.Path == "/api/generate" && r.Method == http.MethodPost:
		s.handleGenerate(w, r)
	case r.Method == http.MethodGet || r.Method == http.MethodHead:
		s.handlePage(w, r)
	default:
		w.Header().Set("Allow", "GET, HEAD, POST")
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
	}
}

// handlePage serves the interface itself: the page at the root, and the two
// assets beside it.
func (s *Server) handlePage(w http.ResponseWriter, r *http.Request) {
	name := "assets/index.html"
	if r.URL.Path != "/" {
		name = "assets/" + r.URL.Path[1:]
	}
	body, err := assets.ReadFile(name)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", contentType(name))
	// the page reads and writes the configuration; a stale copy of it in a
	// cache would show settings that are no longer there
	w.Header().Set("Cache-Control", "no-store")
	_, _ = w.Write(body)
}

func (s *Server) handleState(w http.ResponseWriter) {
	cfg, err := s.read()
	if err != nil {
		s.log.Error("the admin interface cannot read the configuration",
			"path", s.path, "error", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	values := s.schema.Values(cfg)
	body := state{
		Schema:    s.schema,
		Values:    values,
		Path:      s.path,
		Reload:    cfg.General.ReloadConfig,
		Summaries: s.schema.Summaries(values),
	}
	if err := s.writable(); err != nil {
		body.WriteError = err.Error()
	} else {
		body.Writable = true
	}
	writeJSON(w, http.StatusOK, body)
}

// handleApply validates what was posted and writes it. Nothing is applied to a
// running server here: the watcher does that when it sees the new file.
func (s *Server) handleApply(w http.ResponseWriter, r *http.Request) {
	if !s.posted(w, r) {
		return
	}

	var posted map[string]any
	if err := json.NewDecoder(io.LimitReader(r.Body, maxPost)).Decode(&posted); err != nil {
		http.Error(w, "the body is not the configuration: "+err.Error(), http.StatusBadRequest)
		return
	}

	cfg, err := s.schema.Apply(posted)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	// validated the way the file is validated when it is loaded, so that the
	// page reports what -check would report and a file that cannot work is
	// never written
	if err := cfg.Resolved().Validate(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	backup, err := s.write(cfg)
	if err != nil {
		s.log.Error("the admin interface cannot write the configuration",
			"path", s.path, "error", err)
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	s.log.Info("the configuration was written by the admin interface",
		"path", s.path, "backup", backup, "address", addressOf(r))

	writeJSON(w, http.StatusOK, map[string]any{
		"path":   s.path,
		"backup": backup,
		"reload": cfg.General.ReloadConfig,
	})
}

// posted guards everything this server accepts a body on. A cross site form
// cannot set this content type — which is why the uploads are JSON rather than
// multipart — and a cross site fetch that sets it is stopped by a preflight
// this server does not answer.
func (s *Server) posted(w http.ResponseWriter, r *http.Request) bool {
	if r.Header.Get("Content-Type") != "application/json" {
		http.Error(w, "the body has to be application/json", http.StatusUnsupportedMediaType)
		return false
	}
	if origin := r.Header.Get("Origin"); origin != "" && !sameHost(origin, r.Host) {
		s.log.Warn("the admin interface refused a request from another origin",
			"origin", origin, "address", addressOf(r))
		http.Error(w, "Forbidden", http.StatusForbidden)
		return false
	}
	return true
}

// sameHost reports whether an Origin header names the host this request was
// made to. The host is compared rather than the whole origin, so that the check
// still holds when the interface is reached through something that terminates
// TLS in front of it.
func sameHost(origin, host string) bool {
	parsed, err := url.Parse(origin)
	if err != nil {
		return false
	}
	return parsed.Host == host
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func contentType(name string) string {
	switch {
	case hasSuffix(name, ".html"):
		return "text/html; charset=utf-8"
	case hasSuffix(name, ".css"):
		return "text/css; charset=utf-8"
	case hasSuffix(name, ".js"):
		return "text/javascript; charset=utf-8"
	default:
		return "application/octet-stream"
	}
}

func hasSuffix(name, suffix string) bool {
	return len(name) >= len(suffix) && name[len(name)-len(suffix):] == suffix
}

// Assets reports the names of the embedded files, for tests.
func Assets() ([]string, error) {
	var names []string
	err := fs.WalkDir(assets, "assets", func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		names = append(names, path)
		return nil
	})
	return names, err
}

func listenAddress(listener net.Listener) string {
	if tcp, ok := listener.Addr().(*net.TCPAddr); ok {
		return tcp.IP.String()
	}
	return listener.Addr().String()
}

func listenPort(listener net.Listener) int {
	if tcp, ok := listener.Addr().(*net.TCPAddr); ok {
		return tcp.Port
	}
	return 0
}

func addressOf(r *http.Request) string {
	if host, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return host
	}
	return r.RemoteAddr
}
